# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18gqadWHMKpOnLpBy-wmPGt5VqrCpLSf7
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

#Importamos las librerías
import streamlit as st
import pandas as pd
import yfinance as yf

st.title("Mi primera aplicación en Steamlit")

#Lista de ticker inicial
lista_ticker = ["AAPL", "MSFT", "NVDA"]

#Selector
ticker=st.selectbox("Elija la acción", lista_ticker)

#Botón
if st.button("Descargar"):
  data=yf.donwload(ticker,period="1mo")
  st.dataframe(data)