# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18gqadWHMKpOnLpBy-wmPGt5VqrCpLSf7
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

#Importamos las librerías
import streamlit as st
import pandas as pd

st.title("Mi primera aplicación en Steamlit")